config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end

  mount ActionCable.server => '/cable'

  post 'payments/create'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  get 'simple_pages/landing_page'

  post 'simple_pages/thank_you'

  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.search(search_term)
    if Rails.env.development?
      Product.where("name LIKE ?", "%#{search_term}%")
    else Rails.env.production?
      Product.where("name ilike ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
  comments.rating_asc.first
  end

  def average_rating
  comments.average(:rating).to_f
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action only: [:new, :edit, :update, :destroy] do
    redirect_to products_path, alert: 'You need to be an Admin to perform this action!' unless current_user && current_user.admin
  end

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
      logger.debug "My search found #{@products.count} products"
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").page(params[:page]).per_page(3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, class: 'product-form', local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', id: :product_name, placeholder: "Enter Product Name", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control', id: :product_description, placeholder: "Enter Product Description", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :image_url %>
      <%= form.text_field :image_url, class: 'form-control', id: :product_image_url, placeholder: "Enter Product URL", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :price %><br>
      <%= form.text_field :price, class: 'form-control', id: :product_price, placeholder: "Enter Product Price", required: true %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  <div class="form-group">

  </div>
    <p>
      <%= f.label :body, "Comment" %><br>
      <%= f.text_area :body, class: 'form-control' %>
    </p>

    <p>
      <div class="rating"></div>
    </p>
    <p>

      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <div class="col-sm-6 col-md-4" id="product_table">
    <div id="product_table_inner">
      <!-- <% logger.debug "Product: #{product.name}"%> -->
      <% if product.image_url.present? %>
        <%= link_to image_tag(product.image_url, class: "img-responsive"), product %>
      <% end %>
      <h1><%= link_to product.name, product %></h1>
      <p id="product_description"><%= product.description %></p>
      <strong id="product_price">£<%= product.price %></strong>
      <!-- <p><%= link_to 'Show', product %></p> -->
      <!-- <% if signed_in? && current_user.admin? %>
        <p><%= link_to 'Edit', edit_product_path(product) %></p>
        <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %> -->
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<div class="container-fluid">
  <div class="row">
    <% cache(cache_key_for_products) do %>
  <%= render @products %>
<% end %>
  </div>
</div>
<br>

<% if signed_in? && current_user.admin? %>
  <div class="container-fluid">
    <%= link_to 'New Product', new_product_path %>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h1><%= @product.name %></h1>
  </div>
  <div class="row" data-product-id="<%= @product.id %>">
    <div class="col-sm-4">
      <%= image_tag(@product.image_url, class: "img-zoom", data_zoom_image:"@product.image_url") %>
    </div>
    <div class="col-sm-8 product_info">
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <!-- <p>
        <strong>Image url:</strong>
        <%= @product.image_url %>
      </p> -->

      <p>
        <strong>Price:</strong>
        £<%= @product.price %>
      </p>

      <p>
        Average Rating: <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div>
      </p>

      <div>
        <% if user_signed_in? %>
          <%= form_with(url: payments_create_path) do |form| %>
            <%= hidden_field_tag(:product_id, @product.id) %>
            <%= render partial: "shared/stripe_checkout_button", locals: {product: @product}%>
          <% end %>
        <% else %>
          Please <%= link_to 'sign in', new_user_session_path, class: "edit-link" %>
          or <%= link_to 'sign up', new_user_registration_path, class: "edit-link" %> to buy!
        <% end %>
      </div>
    </div>
  </div>


  <div class="row comments">
    <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
    <%= render 'new_comment' %>
    <%= render 'comments' %>
    <%= will_paginate @comments %>
  </div>
  <% if signed_in? && current_user.admin? %>
  <div class="row">
    <button class="btn"><%= link_to 'Edit', edit_product_path(@product) %></button>
    <button class="btn"><%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    <button class="btn"><%= link_to 'Back', products_path %></button>

  </div>
  <% end %>
</div>