config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end

  mount ActionCable.server => '/cable'

  post 'payments/create'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  get 'simple_pages/landing_page'

  post 'simple_pages/thank_you'

  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruthapp</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>

    <!--***********-->
    <!-- NAVBAR -->
    <!--***********-->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="main-nav">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <li><%= link_to "Laurel Cottage Ltd", simple_pages_landing_page_path, class: "navbar-brand" %></li>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", simple_pages_landing_page_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <!-- Search -->
            <li>
              <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
              <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control", placeholder: "Search" %>
            <!-- </li>
            <li> -->
              <%= form.submit 'Search', class: 'btn', id: 'search-btn'%>
              <% end %>
            </li>
            <li>
              <% if user_signed_in?%>
                <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav><!-- END NAV -->

    <header class="container-fluid">
      <div class="row">
        <%= image_tag("LC-header.jpg", id: "header-img") %>
      </div>
    </header>
    <div class="container-fluid">
      <% if notice %>
        <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id="alert" class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>
    </div>

    <!--***********-->
    <!-- SECTIONS --->
    <!--***********-->

    <div class="section container-fluid" id="home">
    <%= yield %>
    </div>
    <footer class="navbar-static-bottom">
  		<div class="row">
  			<div class="col-md-4 col-sm-4">
  				<ul class="footer-nav">
  					<li><a href="#">Back to top</a></li>
  				</ul>
  			</div>
        <div class="col-md-4 col-sm-4">
  					<p>Copyright &copy; 2018 by Ruth Johnston All Rights Reserved</p>
  			</div>
  			<div class="col-md-4 col-sm-4">
  				<ul class="social-links">
  					<li><a href="https://www.facebook.com/LaurelCottage/" target="_blank"><i class="ion-social-facebook"></i></a></li>
  					<li><a href="#" target="_blank"><i class="ion-social-twitter"></i></a></li>
  					<li><a href="#" target="_blank"><i class="ion-social-instagram"></i></a></li>
  				</ul>
  			</div>
  		</div>
  	</footer>
  </body>
</html>